const STONE_PRODUCTS = [
  {
    name: "Dolomitic Travertine",
    image: "assets/images/final_images/img-041.png",
    sizes: "1200×600 / 2400×600 / 2400×1200 mm",
    thickness: "3–5 mm",
    swatches: [
      { label: "Andean White", image: "assets/images/final_images/img-041.png" },
      { label: "Claybank", image: "assets/images/final_images/img-042.png" },
      { label: "Dark Grey", image: "assets/images/final_images/img-043.png" },
      { label: "Andean Red", image: "assets/images/final_images/img-044.jpg" },
    ],
  },
  {
    name: "Linear Travertine",
    image: "assets/images/final_images/img-067.png",
    sizes: "1200×600 / 2400×600 / 2400×1200 mm",
    thickness: "3–5 mm",
    swatches: [
      { label: "Roman White", image: "assets/images/final_images/img-045.png" },
      { label: "Roman Yellow", image: "assets/images/final_images/img-048.png" },
      { label: "Claybank", image: "assets/images/final_images/img-046.png" },
      { label: "Red", image: "assets/images/final_images/img-047.png" },
      { label: "Light Grey", image: "assets/images/final_images/img-049.png" },
    ],
  },
  {
    name: "Romanite",
    image: "assets/images/final_images/img-088.jpg",
    sizes: "1200×600 / 2400×600 / 2400×1200 mm",
    thickness: "3–5 mm",
    swatches: [
      { label: "Cloudy White", image: "assets/images/final_images/img-084.png" },
      { label: "Cloudy Yellow", image: "assets/images/final_images/img-085.png" },
      { label: "Cloudy Grey", image: "assets/images/final_images/img-086.jpg" },
    ],
  },
  {
    name: "Milan Travertine",
    image: "assets/images/final_images/img-109.jpg",
    sizes: "1200×600 / 2400×600 / 2400×1200 mm",
    thickness: "3–5 mm",
    swatches: [
      { label: "White", image: "assets/images/final_images/img-105.png" },
      { label: "Yellow", image: "assets/images/final_images/img-106.png" },
      { label: "Grey", image: "assets/images/final_images/img-107.png" },
    ],
  },
  {
    name: "Ando Cement",
    image: "assets/images/final_images/img-127.png",
    sizes: "1200×600 / 2400×600 / 2400×1200 mm",
    thickness: "3–5 mm",
    swatches: [
      { label: "Cement Grey", image: "assets/images/final_images/img-127.png" },
      { label: "Warm Grey", image: "assets/images/final_images/img-128.png" },
      { label: "Taupe", image: "assets/images/final_images/img-129.png" },
    ],
  },
  {
    name: "Zen Ando Cement Board",
    image: "assets/images/final_images/img-130.png",
    sizes: "1200×600 / 2400×600 / 2400×1200 mm",
    thickness: "3–5 mm",
    swatches: [{ label: "Warm Grey", image: "assets/images/final_images/img-130.png" }],
  },
  {
    name: "Golden Faith",
    image: "assets/images/final_images/img-148.png",
    sizes: "1200×600 / 2400×600 / 2400×1200 mm",
    thickness: "3–5 mm",
    swatches: [
      { label: "Sunset Glow", image: "assets/images/final_images/img-148.png" },
      { label: "Sunset Glow", image: "assets/images/final_images/img-149.png" },
    ],
  },
  {
    name: "Italian Ash Mountain Stone",
    image: "assets/images/final_images/img-166.png",
    sizes: "1200×600 mm",
    thickness: "3–5 mm",
    swatches: [{ label: "Caslan / Normandy Grey", image: "assets/images/final_images/img-166.png" }],
  },
  {
    name: "Lime Stone",
    image: "assets/images/final_images/img-185.png",
    sizes: "1200×600 mm",
    thickness: "3–5 mm",
    swatches: [
      { label: "Dark Grey", image: "assets/images/final_images/img-183.png" },
      { label: "Off-White", image: "assets/images/final_images/img-184.png" },
    ],
  },
  {
    name: "Stream Limestone",
    image: "assets/images/final_images/img-204.png",
    sizes: "1200×600 mm",
    thickness: "3–5 mm",
    swatches: [
      { label: "Dark Grey", image: "assets/images/final_images/img-202.png" },
      { label: "Claybank", image: "assets/images/final_images/img-203.jpg" },
    ],
  },
  {
    name: "Roman Pillar",
    image: "assets/images/final_images/img-224.png",
    sizes: "3000×1200 / 3000×600 mm",
    thickness: "3–9 mm",
    swatches: [
      { label: "Cement Grey", image: "assets/images/final_images/img-221.png" },
      { label: "Claybank", image: "assets/images/final_images/img-223.png" },
      { label: "Bulgari", image: "assets/images/final_images/img-224.png" },
    ],
  },
  {
    name: "Golden Sunset",
    image: "assets/images/final_images/img-246.jpg",
    sizes: "1200×600 mm",
    thickness: "3–5 mm",
    swatches: [
      { label: "Silver Grey", image: "assets/images/final_images/img-242.png" },
      { label: "Dark Grey", image: "assets/images/final_images/img-243.png" },
      { label: "Golden", image: "assets/images/final_images/img-225.png" },
    ],
  },
  {
    name: "Skyline Stone",
    image: "assets/images/final_images/img-251.png",
    sizes: "1200×600 mm",
    thickness: "3–5 mm",
    swatches: [
      { label: "Nile Silver Grey", image: "assets/images/final_images/img-248.png" },
      { label: "Gritty Beige", image: "assets/images/final_images/img-249.png" },
      { label: "Nile Dark Grey", image: "assets/images/final_images/img-250.png" },
    ],
  },
  {
    name: "Rusty Red",
    image: "assets/images/final_images/img-291.png",
    sizes: "1200×600 mm",
    thickness: "3–5 mm",
    swatches: [
      { label: "Red", image: "assets/images/final_images/img-269.png" },
      { label: "Grey", image: "assets/images/final_images/img-270.png" },
      { label: "Red", image: "assets/images/final_images/img-271.png" },
      { label: "Grey", image: "assets/images/final_images/img-272.png" },
      { label: "Red", image: "assets/images/final_images/img-273.png" },
      { label: "Grey", image: "assets/images/final_images/img-274.png" },
    ],
  },
];

const GALLERY_IMAGES = [
  { image: "assets/images/final_images/img-000.png", label: "Magic Stone Collection" },
  { image: "assets/images/final_images/img-066.png", label: "Linear Travertine — Exterior" },
  { image: "assets/images/final_images/img-246.jpg", label: "Golden Sunset — Interior" },
  { image: "assets/images/final_images/img-088.jpg", label: "Romanite — Retail Interior" },
  { image: "assets/images/final_images/img-130.png", label: "Zen Ando Cement Board" },
  { image: "assets/images/final_images/img-291.png", label: "Rusty Red — Landscape" },
  { image: "assets/images/final_images/img-110.jpg", label: "Milan Travertine Application" },
  { image: "assets/images/final_images/img-204.png", label: "Stream Limestone" },
  { image: "assets/images/final_images/img-224.png", label: "Roman Pillar" },
  { image: "assets/images/final_images/img-018.png", label: "Natural Stone Inspiration" },
  { image: "assets/images/final_images/img-020.jpg", label: "Mountain Stone Inspiration" },
  { image: "assets/images/final_images/img-268.png", label: "Skyline Stone Application" },
];
